### ISSUE TITLE
I get error uploading

### ISSUE THREAD

**Issue by krisjaniszakis** [opensourceBIM/ModeltoolsPlugins#3]
Why i get error text when uploading model:
Error uploading to BIMserver:
[{"_type":"SDeserializerPluginConfiguration","description":"IfcStepDeserializer","oid":262185,"pluginDescriptorId":2228278,"rid":1,"settingsId":4653147,"userSetingsId":131080.....

Any clue why it hapens ?

**Comment by rubendel** [comment]
What is the error message? Which version of BIMserver do yo use. Are you using BIMvie.ws?

**Comment by krisjaniszakis** [comment]
Error message at in Sketchup window:
[{"_type":"SDeserializerPluginConfiguration","description":"IfcStepDeserializer","oid":262185,"pluginDescriptorId":2228278,"rid":1,"settingsId":4653147,"userSetingsId":131080.....

Bimserver version is:
Version: 1.3.3

Bimvie.ws
Version: 1.3

**Comment by janbrouwer** [comment]
I think it's a bit too early to try the sketchup uploader.
At the moment it's only tested on one specific BIMserver instance.

**Comment by krisjaniszakis** [comment]
Thanks I fully understand that.

**Comment by janbrouwer** [comment]
I have created a new release, it should be a little more robust.
Do you still get the same error with this version?
