### ISSUE TITLE
Upload after editting not working

### ISSUE THREAD

**Issue by SvSchaijk** [opensourceBIM/ModeltoolsPlugins#5]
Hi,

First I upload a model, get a html back, after I edit my model and try to reupload and make a revision, I dont get a new html back...

**Comment by berlotti** [comment]
Is the new revision actually send to the server or not? (is the problem the creation of a html, or the creation of ifc to send to server?)

**Comment by SvSchaijk** [comment]
Model is not send to the server after editting, no revision is visible on the server

**Comment by berlotti** [comment]
see https://www.dropbox.com/s/gb1xjdgpugjk2ts/SketchUp%20plugin%20BIMserver%20tutorial%20V3.mp4?dl=0

**Comment by janbrouwer** [comment]
Thanks for reporting the issue!
I found an error in closing the upload window.
Please try the new version 0.4.3

**Comment by SvSchaijk** [comment]
Thanks, just tested the new release, it worked. One other thing was changed I noticed, namely the console was viewable some moments, is that ment to be? See this movie: https://www.dropbox.com/s/4dpz5g2jfrt99ua/SketchUp%20plugin%20BIMserver%20tutorial%20V4.mp4?dl=0

**Comment by janbrouwer** [comment]
I'm sorry, that's another error that slipped into the previous version (and probably won't be deleted automatically by SketchUp). I use firebug for testing the javascript in the dialogs and I accidentally included that in the release...
Please remove the contents of this folder (Sketchup 2015 on windows):
%USERPROFILE%\AppData\Roaming\SketchUp\SketchUp 2015\SketchUp\Plugins\opensourceBIM\tools\firebug-lite\
